### ISSUE TITLE
Widget Storto

### ISSUE THREAD

**Issue by ImLeonardoo** [afrux/online-users-widget#1]
![image](https://user-images.githubusercontent.com/91559829/136076772-bb2129ea-9314-46d4-930a-ba52b081a0b7.png)
Il widget non è proporzionato all'icona dell'utente. Inoltre sarebbe bello se fosse possibile inserire solo i nomi degli utenti online, non le icone.

**Comment by SychO9** [comment]
english please, I don't understand what you mean by icons being wrong ? I might add in the future an option to list by display name only.
